# Site settings
title: Meet The Matesics
email: your-email@domain.com
url: https://MeetTheMatesics.com
description: "Wedding website for Domenic Matesic and Jennifer Sukool. April 30th, 2016"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-color: '45, 72, 105'
  secondary-color: '171,136,76'

# Footer settings
footer: #MeetTheMatesics April 30th, 2016

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
